<a href="https://colab.research.google.com/github/Dilajohn/Numpy-Tutorial/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
# converting a list to a numpy array
import numpy as np
arr = np.array(list1)
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [9]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(listarray)
listarray.size # number of elements in an array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


9

In [10]:
listarray.dtype # checking the data type of the values in the array

dtype('int64')

**Creating a 1d array**
1D array => represents a simple sequence of numbers like a vector
np.array([7,2,5,6])
Note:
each dimention is an axis and a 1D array has one axis

In [11]:
arr = np.array([1,2,3,4,5])
print("1D Array")
print(arr)
arr.shape

1D Array
[1 2 3 4 5]


(5,)

**Creating a 2D array(Matrix)**

2D array =>represents a matrix
> agrid of numbers with columns and rows
>has two axes

In [12]:
arr_2d = np.array([[1,2,3,],[4,5,6]])
print("2D Array:")
print(arr_2d)
arr_2d.shape # the number of rows and columns in an array

2D Array:
[[1 2 3]
 [4 5 6]]


(2, 3)

In [14]:
a = np.array([[1,2,3,2],[2,5,82,7],[5,8,7,5]],dtype=np.int32)
print(a)
a.shape #number of rows (axis 0):3 (refers to the horizontal direction in the array)
        #number of columns(axis 1) :4 (refers to the vertical direction in the array)

[[ 1  2  3  2]
 [ 2  5 82  7]
 [ 5  8  7  5]]


(3, 4)

**creating a 3D Arry**
3Darray => represents a tensor
>A collection of matrices stacked together
> has three axes

In [15]:
# Create a 3D array with dimensions (2,3,4)
# 2matrices(layers), 3rows , and 4 columns
arr_3d = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]],dtype=float)
print(arr_3d)
print("shape:",arr_3d.shape)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[13. 14. 15. 16.]
  [17. 18. 19. 20.]
  [21. 22. 23. 24.]]]
shape: (2, 3, 4)


In [16]:
arr_3d.ndim #number of dimensions

3

In [18]:
zeros_3d = np.zeros((2,3,4))
zeros_3d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [19]:
ones_3d = np.ones((2,3,4))
ones_3d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [20]:
random_3d = np.random.random((2,3,4))
random_3d

array([[[0.44545765, 0.69904469, 0.69201143, 0.58963875],
        [0.39593448, 0.90589796, 0.42525804, 0.54632553],
        [0.59292656, 0.0905394 , 0.04183785, 0.05806395]],

       [[0.60849288, 0.08406213, 0.03805683, 0.0465629 ],
        [0.48306814, 0.69897896, 0.99098124, 0.87185   ],
        [0.495479  , 0.9833698 , 0.61957043, 0.89894465]]])

**creating a zero-filled array**

In [22]:
zeros = np.zeros((2,3)) #2 x 3 array of zeros
print("zero-filled array:")
print(zeros)

zero-filled array:
[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
zeros.dtype

dtype('float64')

In [24]:
zeros.shape

(2, 3)

creating an array of ones

In [25]:
ones = np.ones((3,3)) #3x3 array of ones
print("ones-filled Array:")
print(ones)

ones-filled Array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Creating an array of apraticular value**

In [26]:
array_of_threes = np.full((5,4),3) #5x4 array filled with 3
print(array_of_threes)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [28]:
#create a 1D array of length 5 , filled with 2 and with dtype float64
array_of_twos_float = np.full(5,2, dtype = np.float64)
print(array_of_twos_float)


[2. 2. 2. 2. 2.]


In [29]:
# creating an empty array of shape (4,6)
empty_array = np.empty((4,6))# creates an numpy array without initializing its values
print(empty_array)

[[0.44545765 0.69904469 0.69201143 0.58963875 0.39593448 0.90589796]
 [0.42525804 0.54632553 0.59292656 0.0905394  0.04183785 0.05806395]
 [0.60849288 0.08406213 0.03805683 0.0465629  0.48306814 0.69897896]
 [0.99098124 0.87185    0.495479   0.9833698  0.61957043 0.89894465]]


**Identy matrix**