<a href="https://colab.research.google.com/github/Dilajohn/Numpy-Tutorial/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
# converting a list to a numpy array
import numpy as np
arr = np.array(list1)
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [9]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(listarray)
listarray.size # number of elements in an array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


9

In [10]:
listarray.dtype # checking the data type of the values in the array

dtype('int64')

**Creating a 1d array**
1D array => represents a simple sequence of numbers like a vector
np.array([7,2,5,6])
Note:
each dimention is an axis and a 1D array has one axis

In [11]:
arr = np.array([1,2,3,4,5])
print("1D Array")
print(arr)
arr.shape

1D Array
[1 2 3 4 5]


(5,)

**Creating a 2D array(Matrix)**

2D array =>represents a matrix
> agrid of numbers with columns and rows
>has two axes

In [12]:
arr_2d = np.array([[1,2,3,],[4,5,6]])
print("2D Array:")
print(arr_2d)
arr_2d.shape # the number of rows and columns in an array

2D Array:
[[1 2 3]
 [4 5 6]]


(2, 3)

In [14]:
a = np.array([[1,2,3,2],[2,5,82,7],[5,8,7,5]],dtype=np.int32)
print(a)
a.shape #number of rows (axis 0):3 (refers to the horizontal direction in the array)
        #number of columns(axis 1) :4 (refers to the vertical direction in the array)

[[ 1  2  3  2]
 [ 2  5 82  7]
 [ 5  8  7  5]]


(3, 4)

**creating a 3D Arry**
3Darray => represents a tensor
>A collection of matrices stacked together
> has three axes

In [ ]:
# Create a 3D array with dimensions (2,3,4)
# 2matrices(layers), 3rows , and 4 columns
arr_3d = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]],dtype=float)
print(arr_3d)
print("shape:",arr_3d.shape)